/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserId = IDL.Nat;
export const AnalysisType = IDL.Variant({
  'manual' : IDL.Null,
  'product' : IDL.Null,
});
export const Timestamp = IDL.Int;
export const ReviewAnalysis = IDL.Record({
  'id' : IDL.Nat,
  'patterns' : IDL.Vec(IDL.Text),
  'userId' : UserId,
  'analysisType' : AnalysisType,
  'explanation' : IDL.Text,
  'createdAt' : Timestamp,
  'trustScore' : IDL.Float64,
  'reviewText' : IDL.Text,
  'fakeScore' : IDL.Float64,
  'confidence' : IDL.Float64,
});
export const Result__1_4 = IDL.Variant({
  'ok' : ReviewAnalysis,
  'err' : IDL.Text,
});
export const TrustBadge = IDL.Variant({
  'trusted' : IDL.Null,
  'caution' : IDL.Null,
  'risky' : IDL.Null,
});
export const ProductCheck = IDL.Record({
  'id' : IDL.Nat,
  'productUrl' : IDL.Text,
  'fakePercentage' : IDL.Float64,
  'userId' : UserId,
  'createdAt' : Timestamp,
  'trustBadge' : TrustBadge,
  'reviewCount' : IDL.Nat,
  'adjustedRating' : IDL.Float64,
  'originalRating' : IDL.Float64,
});
export const Result__1_9 = IDL.Variant({
  'ok' : ProductCheck,
  'err' : IDL.Text,
});
export const Result__1_8 = IDL.Variant({ 'ok' : IDL.Bool, 'err' : IDL.Text });
export const TrustBadgeResult = IDL.Record({
  'badgeCode' : IDL.Text,
  'trustStatus' : TrustBadge,
  'score' : IDL.Float64,
});
export const Result__1_7 = IDL.Variant({
  'ok' : TrustBadgeResult,
  'err' : IDL.Text,
});
export const WeeklyTrendEntry = IDL.Record({
  'count' : IDL.Nat,
  'week' : IDL.Text,
  'avgFake' : IDL.Float64,
});
export const PlatformStats = IDL.Record({
  'totalAnalyses' : IDL.Nat,
  'weeklyTrend' : IDL.Vec(WeeklyTrendEntry),
  'totalUsers' : IDL.Nat,
  'averageFakeScore' : IDL.Float64,
});
export const Result__1_6 = IDL.Variant({
  'ok' : PlatformStats,
  'err' : IDL.Text,
});
export const AdminUserEntry = IDL.Record({
  'user' : IDL.Record({
    'id' : UserId,
    'createdAt' : Timestamp,
    'role' : IDL.Variant({
      'admin' : IDL.Null,
      'customer' : IDL.Null,
      'seller' : IDL.Null,
    }),
    'email' : IDL.Text,
    'passwordHash' : IDL.Text,
    'analysisCount' : IDL.Nat,
  }),
  'analysisCount' : IDL.Nat,
});
export const Result__1_5 = IDL.Variant({
  'ok' : IDL.Vec(AdminUserEntry),
  'err' : IDL.Text,
});
export const DashboardStats = IDL.Record({
  'totalAnalyses' : IDL.Nat,
  'realCount' : IDL.Nat,
  'fakeCount' : IDL.Nat,
  'weeklyTrend' : IDL.Vec(WeeklyTrendEntry),
  'averageFakeScore' : IDL.Float64,
});
export const Result__1_3 = IDL.Variant({
  'ok' : DashboardStats,
  'err' : IDL.Text,
});
export const SuspiciousProduct = IDL.Record({
  'url' : IDL.Text,
  'count' : IDL.Nat,
  'avgFake' : IDL.Float64,
});
export const Result__1_2 = IDL.Variant({
  'ok' : IDL.Vec(SuspiciousProduct),
  'err' : IDL.Text,
});
export const Result__1_1 = IDL.Variant({
  'ok' : IDL.Vec(ReviewAnalysis),
  'err' : IDL.Text,
});
export const Result__1 = IDL.Variant({
  'ok' : IDL.Vec(ProductCheck),
  'err' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'customer' : IDL.Null,
  'seller' : IDL.Null,
});
export const LoginResult = IDL.Record({
  'token' : IDL.Text,
  'userId' : UserId,
  'role' : UserRole,
});
export const Result_2 = IDL.Variant({ 'ok' : LoginResult, 'err' : IDL.Text });
export const SignupResult = IDL.Record({
  'token' : IDL.Text,
  'userId' : UserId,
});
export const Result_1 = IDL.Variant({ 'ok' : SignupResult, 'err' : IDL.Text });
export const SessionInfo = IDL.Record({ 'userId' : UserId, 'role' : UserRole });
export const Result = IDL.Variant({ 'ok' : SessionInfo, 'err' : IDL.Text });

export const idlService = IDL.Service({
  'analyzeReview' : IDL.Func([IDL.Text, IDL.Text], [Result__1_4], []),
  'checkProductUrl' : IDL.Func([IDL.Text, IDL.Text], [Result__1_9], []),
  'deleteAnalysis' : IDL.Func([IDL.Text, IDL.Nat], [Result__1_8], []),
  'deleteUser' : IDL.Func([IDL.Text, IDL.Nat], [Result__1_8], []),
  'generateTrustBadge' : IDL.Func([IDL.Text, IDL.Text], [Result__1_7], []),
  'getAdminStats' : IDL.Func([IDL.Text], [Result__1_6], []),
  'getAdminUsers' : IDL.Func([IDL.Text, IDL.Nat, IDL.Nat], [Result__1_5], []),
  'getAnalysisById' : IDL.Func([IDL.Text, IDL.Nat], [Result__1_4], []),
  'getDashboardStats' : IDL.Func([IDL.Text], [Result__1_3], []),
  'getTrendingSuspiciousProducts' : IDL.Func([IDL.Text], [Result__1_2], []),
  'getUserAnalyses' : IDL.Func([IDL.Text, IDL.Nat, IDL.Nat], [Result__1_1], []),
  'getUserProductChecks' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Nat],
      [Result__1],
      [],
    ),
  'login' : IDL.Func([IDL.Text, IDL.Text], [Result_2], []),
  'signup' : IDL.Func([IDL.Text, IDL.Text, UserRole], [Result_1], []),
  'validateSession' : IDL.Func([IDL.Text], [Result], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserId = IDL.Nat;
  const AnalysisType = IDL.Variant({
    'manual' : IDL.Null,
    'product' : IDL.Null,
  });
  const Timestamp = IDL.Int;
  const ReviewAnalysis = IDL.Record({
    'id' : IDL.Nat,
    'patterns' : IDL.Vec(IDL.Text),
    'userId' : UserId,
    'analysisType' : AnalysisType,
    'explanation' : IDL.Text,
    'createdAt' : Timestamp,
    'trustScore' : IDL.Float64,
    'reviewText' : IDL.Text,
    'fakeScore' : IDL.Float64,
    'confidence' : IDL.Float64,
  });
  const Result__1_4 = IDL.Variant({ 'ok' : ReviewAnalysis, 'err' : IDL.Text });
  const TrustBadge = IDL.Variant({
    'trusted' : IDL.Null,
    'caution' : IDL.Null,
    'risky' : IDL.Null,
  });
  const ProductCheck = IDL.Record({
    'id' : IDL.Nat,
    'productUrl' : IDL.Text,
    'fakePercentage' : IDL.Float64,
    'userId' : UserId,
    'createdAt' : Timestamp,
    'trustBadge' : TrustBadge,
    'reviewCount' : IDL.Nat,
    'adjustedRating' : IDL.Float64,
    'originalRating' : IDL.Float64,
  });
  const Result__1_9 = IDL.Variant({ 'ok' : ProductCheck, 'err' : IDL.Text });
  const Result__1_8 = IDL.Variant({ 'ok' : IDL.Bool, 'err' : IDL.Text });
  const TrustBadgeResult = IDL.Record({
    'badgeCode' : IDL.Text,
    'trustStatus' : TrustBadge,
    'score' : IDL.Float64,
  });
  const Result__1_7 = IDL.Variant({
    'ok' : TrustBadgeResult,
    'err' : IDL.Text,
  });
  const WeeklyTrendEntry = IDL.Record({
    'count' : IDL.Nat,
    'week' : IDL.Text,
    'avgFake' : IDL.Float64,
  });
  const PlatformStats = IDL.Record({
    'totalAnalyses' : IDL.Nat,
    'weeklyTrend' : IDL.Vec(WeeklyTrendEntry),
    'totalUsers' : IDL.Nat,
    'averageFakeScore' : IDL.Float64,
  });
  const Result__1_6 = IDL.Variant({ 'ok' : PlatformStats, 'err' : IDL.Text });
  const AdminUserEntry = IDL.Record({
    'user' : IDL.Record({
      'id' : UserId,
      'createdAt' : Timestamp,
      'role' : IDL.Variant({
        'admin' : IDL.Null,
        'customer' : IDL.Null,
        'seller' : IDL.Null,
      }),
      'email' : IDL.Text,
      'passwordHash' : IDL.Text,
      'analysisCount' : IDL.Nat,
    }),
    'analysisCount' : IDL.Nat,
  });
  const Result__1_5 = IDL.Variant({
    'ok' : IDL.Vec(AdminUserEntry),
    'err' : IDL.Text,
  });
  const DashboardStats = IDL.Record({
    'totalAnalyses' : IDL.Nat,
    'realCount' : IDL.Nat,
    'fakeCount' : IDL.Nat,
    'weeklyTrend' : IDL.Vec(WeeklyTrendEntry),
    'averageFakeScore' : IDL.Float64,
  });
  const Result__1_3 = IDL.Variant({ 'ok' : DashboardStats, 'err' : IDL.Text });
  const SuspiciousProduct = IDL.Record({
    'url' : IDL.Text,
    'count' : IDL.Nat,
    'avgFake' : IDL.Float64,
  });
  const Result__1_2 = IDL.Variant({
    'ok' : IDL.Vec(SuspiciousProduct),
    'err' : IDL.Text,
  });
  const Result__1_1 = IDL.Variant({
    'ok' : IDL.Vec(ReviewAnalysis),
    'err' : IDL.Text,
  });
  const Result__1 = IDL.Variant({
    'ok' : IDL.Vec(ProductCheck),
    'err' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'customer' : IDL.Null,
    'seller' : IDL.Null,
  });
  const LoginResult = IDL.Record({
    'token' : IDL.Text,
    'userId' : UserId,
    'role' : UserRole,
  });
  const Result_2 = IDL.Variant({ 'ok' : LoginResult, 'err' : IDL.Text });
  const SignupResult = IDL.Record({ 'token' : IDL.Text, 'userId' : UserId });
  const Result_1 = IDL.Variant({ 'ok' : SignupResult, 'err' : IDL.Text });
  const SessionInfo = IDL.Record({ 'userId' : UserId, 'role' : UserRole });
  const Result = IDL.Variant({ 'ok' : SessionInfo, 'err' : IDL.Text });
  
  return IDL.Service({
    'analyzeReview' : IDL.Func([IDL.Text, IDL.Text], [Result__1_4], []),
    'checkProductUrl' : IDL.Func([IDL.Text, IDL.Text], [Result__1_9], []),
    'deleteAnalysis' : IDL.Func([IDL.Text, IDL.Nat], [Result__1_8], []),
    'deleteUser' : IDL.Func([IDL.Text, IDL.Nat], [Result__1_8], []),
    'generateTrustBadge' : IDL.Func([IDL.Text, IDL.Text], [Result__1_7], []),
    'getAdminStats' : IDL.Func([IDL.Text], [Result__1_6], []),
    'getAdminUsers' : IDL.Func([IDL.Text, IDL.Nat, IDL.Nat], [Result__1_5], []),
    'getAnalysisById' : IDL.Func([IDL.Text, IDL.Nat], [Result__1_4], []),
    'getDashboardStats' : IDL.Func([IDL.Text], [Result__1_3], []),
    'getTrendingSuspiciousProducts' : IDL.Func([IDL.Text], [Result__1_2], []),
    'getUserAnalyses' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Nat],
        [Result__1_1],
        [],
      ),
    'getUserProductChecks' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Nat],
        [Result__1],
        [],
      ),
    'login' : IDL.Func([IDL.Text, IDL.Text], [Result_2], []),
    'signup' : IDL.Func([IDL.Text, IDL.Text, UserRole], [Result_1], []),
    'validateSession' : IDL.Func([IDL.Text], [Result], []),
  });
};

export const init = ({ IDL }) => { return []; };