/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AdminUserEntry {
  'user' : {
    'id' : UserId,
    'createdAt' : Timestamp,
    'role' : { 'admin' : null } |
      { 'customer' : null } |
      { 'seller' : null },
    'email' : string,
    'passwordHash' : string,
    'analysisCount' : bigint,
  },
  'analysisCount' : bigint,
}
export type AnalysisType = { 'manual' : null } |
  { 'product' : null };
export interface DashboardStats {
  'totalAnalyses' : bigint,
  'realCount' : bigint,
  'fakeCount' : bigint,
  'weeklyTrend' : Array<WeeklyTrendEntry>,
  'averageFakeScore' : number,
}
export interface LoginResult {
  'token' : string,
  'userId' : UserId,
  'role' : UserRole,
}
export interface PlatformStats {
  'totalAnalyses' : bigint,
  'weeklyTrend' : Array<WeeklyTrendEntry>,
  'totalUsers' : bigint,
  'averageFakeScore' : number,
}
export interface ProductCheck {
  'id' : bigint,
  'productUrl' : string,
  'fakePercentage' : number,
  'userId' : UserId,
  'createdAt' : Timestamp,
  'trustBadge' : TrustBadge,
  'reviewCount' : bigint,
  'adjustedRating' : number,
  'originalRating' : number,
}
export type Result = { 'ok' : SessionInfo } |
  { 'err' : string };
export type Result_1 = { 'ok' : SignupResult } |
  { 'err' : string };
export type Result_2 = { 'ok' : LoginResult } |
  { 'err' : string };
export type Result__1 = { 'ok' : Array<ProductCheck> } |
  { 'err' : string };
export type Result__1_1 = { 'ok' : Array<ReviewAnalysis> } |
  { 'err' : string };
export type Result__1_2 = { 'ok' : Array<SuspiciousProduct> } |
  { 'err' : string };
export type Result__1_3 = { 'ok' : DashboardStats } |
  { 'err' : string };
export type Result__1_4 = { 'ok' : ReviewAnalysis } |
  { 'err' : string };
export type Result__1_5 = { 'ok' : Array<AdminUserEntry> } |
  { 'err' : string };
export type Result__1_6 = { 'ok' : PlatformStats } |
  { 'err' : string };
export type Result__1_7 = { 'ok' : TrustBadgeResult } |
  { 'err' : string };
export type Result__1_8 = { 'ok' : boolean } |
  { 'err' : string };
export type Result__1_9 = { 'ok' : ProductCheck } |
  { 'err' : string };
export interface ReviewAnalysis {
  'id' : bigint,
  'patterns' : Array<string>,
  'userId' : UserId,
  'analysisType' : AnalysisType,
  'explanation' : string,
  'createdAt' : Timestamp,
  'trustScore' : number,
  'reviewText' : string,
  'fakeScore' : number,
  'confidence' : number,
}
export interface SessionInfo { 'userId' : UserId, 'role' : UserRole }
export interface SignupResult { 'token' : string, 'userId' : UserId }
export interface SuspiciousProduct {
  'url' : string,
  'count' : bigint,
  'avgFake' : number,
}
export type Timestamp = bigint;
export type TrustBadge = { 'trusted' : null } |
  { 'caution' : null } |
  { 'risky' : null };
export interface TrustBadgeResult {
  'badgeCode' : string,
  'trustStatus' : TrustBadge,
  'score' : number,
}
export type UserId = bigint;
export type UserRole = { 'admin' : null } |
  { 'customer' : null } |
  { 'seller' : null };
export interface WeeklyTrendEntry {
  'count' : bigint,
  'week' : string,
  'avgFake' : number,
}
export interface _SERVICE {
  'analyzeReview' : ActorMethod<[string, string], Result__1_4>,
  'checkProductUrl' : ActorMethod<[string, string], Result__1_9>,
  'deleteAnalysis' : ActorMethod<[string, bigint], Result__1_8>,
  'deleteUser' : ActorMethod<[string, bigint], Result__1_8>,
  'generateTrustBadge' : ActorMethod<[string, string], Result__1_7>,
  'getAdminStats' : ActorMethod<[string], Result__1_6>,
  'getAdminUsers' : ActorMethod<[string, bigint, bigint], Result__1_5>,
  'getAnalysisById' : ActorMethod<[string, bigint], Result__1_4>,
  'getDashboardStats' : ActorMethod<[string], Result__1_3>,
  'getTrendingSuspiciousProducts' : ActorMethod<[string], Result__1_2>,
  'getUserAnalyses' : ActorMethod<[string, bigint, bigint], Result__1_1>,
  'getUserProductChecks' : ActorMethod<[string, bigint, bigint], Result__1>,
  'login' : ActorMethod<[string, string], Result_2>,
  'signup' : ActorMethod<[string, string, UserRole], Result_1>,
  'validateSession' : ActorMethod<[string], Result>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];