/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface TrustBadgeResult {
    badgeCode: string;
    trustStatus: TrustBadge;
    score: number;
}
export type Timestamp = bigint;
export type Result_2 = {
    __kind__: "ok";
    ok: LoginResult;
} | {
    __kind__: "err";
    err: string;
};
export type Result__1_8 = {
    __kind__: "ok";
    ok: boolean;
} | {
    __kind__: "err";
    err: string;
};
export type Result__1 = {
    __kind__: "ok";
    ok: Array<ProductCheck>;
} | {
    __kind__: "err";
    err: string;
};
export interface AdminUserEntry {
    user: {
        id: UserId;
        createdAt: Timestamp;
        role: Variant_admin_customer_seller;
        email: string;
        passwordHash: string;
        analysisCount: bigint;
    };
    analysisCount: bigint;
}
export type Result__1_7 = {
    __kind__: "ok";
    ok: TrustBadgeResult;
} | {
    __kind__: "err";
    err: string;
};
export type Result_1 = {
    __kind__: "ok";
    ok: SignupResult;
} | {
    __kind__: "err";
    err: string;
};
export interface SessionInfo {
    userId: UserId;
    role: UserRole;
}
export interface SignupResult {
    token: string;
    userId: UserId;
}
export type Result__1_9 = {
    __kind__: "ok";
    ok: ProductCheck;
} | {
    __kind__: "err";
    err: string;
};
export type Result__1_2 = {
    __kind__: "ok";
    ok: Array<SuspiciousProduct>;
} | {
    __kind__: "err";
    err: string;
};
export interface PlatformStats {
    totalAnalyses: bigint;
    weeklyTrend: Array<WeeklyTrendEntry>;
    totalUsers: bigint;
    averageFakeScore: number;
}
export type Result__1_4 = {
    __kind__: "ok";
    ok: ReviewAnalysis;
} | {
    __kind__: "err";
    err: string;
};
export type Result__1_1 = {
    __kind__: "ok";
    ok: Array<ReviewAnalysis>;
} | {
    __kind__: "err";
    err: string;
};
export type Result__1_3 = {
    __kind__: "ok";
    ok: DashboardStats;
} | {
    __kind__: "err";
    err: string;
};
export interface DashboardStats {
    totalAnalyses: bigint;
    realCount: bigint;
    fakeCount: bigint;
    weeklyTrend: Array<WeeklyTrendEntry>;
    averageFakeScore: number;
}
export type UserId = bigint;
export type Result__1_6 = {
    __kind__: "ok";
    ok: PlatformStats;
} | {
    __kind__: "err";
    err: string;
};
export type Result = {
    __kind__: "ok";
    ok: SessionInfo;
} | {
    __kind__: "err";
    err: string;
};
export interface SuspiciousProduct {
    url: string;
    count: bigint;
    avgFake: number;
}
export interface LoginResult {
    token: string;
    userId: UserId;
    role: UserRole;
}
export type Result__1_5 = {
    __kind__: "ok";
    ok: Array<AdminUserEntry>;
} | {
    __kind__: "err";
    err: string;
};
export interface WeeklyTrendEntry {
    count: bigint;
    week: string;
    avgFake: number;
}
export interface ReviewAnalysis {
    id: bigint;
    patterns: Array<string>;
    userId: UserId;
    analysisType: AnalysisType;
    explanation: string;
    createdAt: Timestamp;
    trustScore: number;
    reviewText: string;
    fakeScore: number;
    confidence: number;
}
export interface ProductCheck {
    id: bigint;
    productUrl: string;
    fakePercentage: number;
    userId: UserId;
    createdAt: Timestamp;
    trustBadge: TrustBadge;
    reviewCount: bigint;
    adjustedRating: number;
    originalRating: number;
}
export enum AnalysisType {
    manual = "manual",
    product = "product"
}
export enum TrustBadge {
    trusted = "trusted",
    caution = "caution",
    risky = "risky"
}
export enum Variant_admin_customer_seller {
    admin = "admin",
    customer = "customer",
    seller = "seller"
}
export interface backendInterface {
    analyzeReview(token: string, reviewText: string): Promise<Result__1_4>;
    checkProductUrl(token: string, productUrl: string): Promise<Result__1_9>;
    deleteAnalysis(token: string, analysisId: bigint): Promise<Result__1_8>;
    deleteUser(token: string, targetUserId: bigint): Promise<Result__1_8>;
    generateTrustBadge(token: string, productUrl: string): Promise<Result__1_7>;
    getAdminStats(token: string): Promise<Result__1_6>;
    getAdminUsers(token: string, limit: bigint, offset: bigint): Promise<Result__1_5>;
    getAnalysisById(token: string, analysisId: bigint): Promise<Result__1_4>;
    getDashboardStats(token: string): Promise<Result__1_3>;
    getTrendingSuspiciousProducts(token: string): Promise<Result__1_2>;
    getUserAnalyses(token: string, limit: bigint, offset: bigint): Promise<Result__1_1>;
    getUserProductChecks(token: string, limit: bigint, offset: bigint): Promise<Result__1>;
    login(email: string, password: string): Promise<Result_2>;
    signup(email: string, password: string, role: UserRole): Promise<Result_1>;
    validateSession(token: string): Promise<Result>;
}
import type { AdminUserEntry as _AdminUserEntry, AnalysisType as _AnalysisType, DashboardStats as _DashboardStats, LoginResult as _LoginResult, PlatformStats as _PlatformStats, ProductCheck as _ProductCheck, Result as _Result, Result_1 as _Result_1, Result_2 as _Result_2, Result__1 as _Result__1, Result__1_1 as _Result__1_1, Result__1_2 as _Result__1_2, Result__1_3 as _Result__1_3, Result__1_4 as _Result__1_4, Result__1_5 as _Result__1_5, Result__1_6 as _Result__1_6, Result__1_7 as _Result__1_7, Result__1_8 as _Result__1_8, Result__1_9 as _Result__1_9, ReviewAnalysis as _ReviewAnalysis, SessionInfo as _SessionInfo, SignupResult as _SignupResult, SuspiciousProduct as _SuspiciousProduct, Timestamp as _Timestamp, TrustBadge as _TrustBadge, TrustBadgeResult as _TrustBadgeResult, UserId as _UserId, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async analyzeReview(arg0: string, arg1: string): Promise<Result__1_4> {
        if (this.processError) {
            try {
                const result = await this.actor.analyzeReview(arg0, arg1);
                return from_candid_Result__1_4_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.analyzeReview(arg0, arg1);
            return from_candid_Result__1_4_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async checkProductUrl(arg0: string, arg1: string): Promise<Result__1_9> {
        if (this.processError) {
            try {
                const result = await this.actor.checkProductUrl(arg0, arg1);
                return from_candid_Result__1_9_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.checkProductUrl(arg0, arg1);
            return from_candid_Result__1_9_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteAnalysis(arg0: string, arg1: bigint): Promise<Result__1_8> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteAnalysis(arg0, arg1);
                return from_candid_Result__1_8_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteAnalysis(arg0, arg1);
            return from_candid_Result__1_8_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteUser(arg0: string, arg1: bigint): Promise<Result__1_8> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteUser(arg0, arg1);
                return from_candid_Result__1_8_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteUser(arg0, arg1);
            return from_candid_Result__1_8_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async generateTrustBadge(arg0: string, arg1: string): Promise<Result__1_7> {
        if (this.processError) {
            try {
                const result = await this.actor.generateTrustBadge(arg0, arg1);
                return from_candid_Result__1_7_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.generateTrustBadge(arg0, arg1);
            return from_candid_Result__1_7_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAdminStats(arg0: string): Promise<Result__1_6> {
        if (this.processError) {
            try {
                const result = await this.actor.getAdminStats(arg0);
                return from_candid_Result__1_6_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAdminStats(arg0);
            return from_candid_Result__1_6_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAdminUsers(arg0: string, arg1: bigint, arg2: bigint): Promise<Result__1_5> {
        if (this.processError) {
            try {
                const result = await this.actor.getAdminUsers(arg0, arg1, arg2);
                return from_candid_Result__1_5_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAdminUsers(arg0, arg1, arg2);
            return from_candid_Result__1_5_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAnalysisById(arg0: string, arg1: bigint): Promise<Result__1_4> {
        if (this.processError) {
            try {
                const result = await this.actor.getAnalysisById(arg0, arg1);
                return from_candid_Result__1_4_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAnalysisById(arg0, arg1);
            return from_candid_Result__1_4_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDashboardStats(arg0: string): Promise<Result__1_3> {
        if (this.processError) {
            try {
                const result = await this.actor.getDashboardStats(arg0);
                return from_candid_Result__1_3_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDashboardStats(arg0);
            return from_candid_Result__1_3_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTrendingSuspiciousProducts(arg0: string): Promise<Result__1_2> {
        if (this.processError) {
            try {
                const result = await this.actor.getTrendingSuspiciousProducts(arg0);
                return from_candid_Result__1_2_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTrendingSuspiciousProducts(arg0);
            return from_candid_Result__1_2_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserAnalyses(arg0: string, arg1: bigint, arg2: bigint): Promise<Result__1_1> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserAnalyses(arg0, arg1, arg2);
                return from_candid_Result__1_1_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserAnalyses(arg0, arg1, arg2);
            return from_candid_Result__1_1_n32(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProductChecks(arg0: string, arg1: bigint, arg2: bigint): Promise<Result__1> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProductChecks(arg0, arg1, arg2);
                return from_candid_Result__1_n35(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProductChecks(arg0, arg1, arg2);
            return from_candid_Result__1_n35(this._uploadFile, this._downloadFile, result);
        }
    }
    async login(arg0: string, arg1: string): Promise<Result_2> {
        if (this.processError) {
            try {
                const result = await this.actor.login(arg0, arg1);
                return from_candid_Result_2_n38(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.login(arg0, arg1);
            return from_candid_Result_2_n38(this._uploadFile, this._downloadFile, result);
        }
    }
    async signup(arg0: string, arg1: string, arg2: UserRole): Promise<Result_1> {
        if (this.processError) {
            try {
                const result = await this.actor.signup(arg0, arg1, to_candid_UserRole_n43(this._uploadFile, this._downloadFile, arg2));
                return from_candid_Result_1_n45(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.signup(arg0, arg1, to_candid_UserRole_n43(this._uploadFile, this._downloadFile, arg2));
            return from_candid_Result_1_n45(this._uploadFile, this._downloadFile, result);
        }
    }
    async validateSession(arg0: string): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.validateSession(arg0);
                return from_candid_Result_n47(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.validateSession(arg0);
            return from_candid_Result_n47(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_AdminUserEntry_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AdminUserEntry): AdminUserEntry {
    return from_candid_record_n25(_uploadFile, _downloadFile, value);
}
function from_candid_AnalysisType_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AnalysisType): AnalysisType {
    return from_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function from_candid_LoginResult_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _LoginResult): LoginResult {
    return from_candid_record_n41(_uploadFile, _downloadFile, value);
}
function from_candid_ProductCheck_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ProductCheck): ProductCheck {
    return from_candid_record_n10(_uploadFile, _downloadFile, value);
}
function from_candid_Result_1_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result_1): Result_1 {
    return from_candid_variant_n46(_uploadFile, _downloadFile, value);
}
function from_candid_Result_2_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result_2): Result_2 {
    return from_candid_variant_n39(_uploadFile, _downloadFile, value);
}
function from_candid_Result__1_1_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result__1_1): Result__1_1 {
    return from_candid_variant_n33(_uploadFile, _downloadFile, value);
}
function from_candid_Result__1_2_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result__1_2): Result__1_2 {
    return from_candid_variant_n31(_uploadFile, _downloadFile, value);
}
function from_candid_Result__1_3_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result__1_3): Result__1_3 {
    return from_candid_variant_n29(_uploadFile, _downloadFile, value);
}
function from_candid_Result__1_4_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result__1_4): Result__1_4 {
    return from_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function from_candid_Result__1_5_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result__1_5): Result__1_5 {
    return from_candid_variant_n22(_uploadFile, _downloadFile, value);
}
function from_candid_Result__1_6_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result__1_6): Result__1_6 {
    return from_candid_variant_n20(_uploadFile, _downloadFile, value);
}
function from_candid_Result__1_7_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result__1_7): Result__1_7 {
    return from_candid_variant_n16(_uploadFile, _downloadFile, value);
}
function from_candid_Result__1_8_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result__1_8): Result__1_8 {
    return from_candid_variant_n14(_uploadFile, _downloadFile, value);
}
function from_candid_Result__1_9_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result__1_9): Result__1_9 {
    return from_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function from_candid_Result__1_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result__1): Result__1 {
    return from_candid_variant_n36(_uploadFile, _downloadFile, value);
}
function from_candid_Result_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result): Result {
    return from_candid_variant_n48(_uploadFile, _downloadFile, value);
}
function from_candid_ReviewAnalysis_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ReviewAnalysis): ReviewAnalysis {
    return from_candid_record_n4(_uploadFile, _downloadFile, value);
}
function from_candid_SessionInfo_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SessionInfo): SessionInfo {
    return from_candid_record_n50(_uploadFile, _downloadFile, value);
}
function from_candid_TrustBadgeResult_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TrustBadgeResult): TrustBadgeResult {
    return from_candid_record_n18(_uploadFile, _downloadFile, value);
}
function from_candid_TrustBadge_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TrustBadge): TrustBadge {
    return from_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n27(_uploadFile, _downloadFile, value);
}
function from_candid_record_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    productUrl: string;
    fakePercentage: number;
    userId: _UserId;
    createdAt: _Timestamp;
    trustBadge: _TrustBadge;
    reviewCount: bigint;
    adjustedRating: number;
    originalRating: number;
}): {
    id: bigint;
    productUrl: string;
    fakePercentage: number;
    userId: UserId;
    createdAt: Timestamp;
    trustBadge: TrustBadge;
    reviewCount: bigint;
    adjustedRating: number;
    originalRating: number;
} {
    return {
        id: value.id,
        productUrl: value.productUrl,
        fakePercentage: value.fakePercentage,
        userId: value.userId,
        createdAt: value.createdAt,
        trustBadge: from_candid_TrustBadge_n11(_uploadFile, _downloadFile, value.trustBadge),
        reviewCount: value.reviewCount,
        adjustedRating: value.adjustedRating,
        originalRating: value.originalRating
    };
}
function from_candid_record_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    badgeCode: string;
    trustStatus: _TrustBadge;
    score: number;
}): {
    badgeCode: string;
    trustStatus: TrustBadge;
    score: number;
} {
    return {
        badgeCode: value.badgeCode,
        trustStatus: from_candid_TrustBadge_n11(_uploadFile, _downloadFile, value.trustStatus),
        score: value.score
    };
}
function from_candid_record_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    user: {
        id: _UserId;
        createdAt: _Timestamp;
        role: {
            admin: null;
        } | {
            customer: null;
        } | {
            seller: null;
        };
        email: string;
        passwordHash: string;
        analysisCount: bigint;
    };
    analysisCount: bigint;
}): {
    user: {
        id: UserId;
        createdAt: Timestamp;
        role: Variant_admin_customer_seller;
        email: string;
        passwordHash: string;
        analysisCount: bigint;
    };
    analysisCount: bigint;
} {
    return {
        user: from_candid_record_n26(_uploadFile, _downloadFile, value.user),
        analysisCount: value.analysisCount
    };
}
function from_candid_record_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _UserId;
    createdAt: _Timestamp;
    role: {
        admin: null;
    } | {
        customer: null;
    } | {
        seller: null;
    };
    email: string;
    passwordHash: string;
    analysisCount: bigint;
}): {
    id: UserId;
    createdAt: Timestamp;
    role: Variant_admin_customer_seller;
    email: string;
    passwordHash: string;
    analysisCount: bigint;
} {
    return {
        id: value.id,
        createdAt: value.createdAt,
        role: from_candid_variant_n27(_uploadFile, _downloadFile, value.role),
        email: value.email,
        passwordHash: value.passwordHash,
        analysisCount: value.analysisCount
    };
}
function from_candid_record_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    patterns: Array<string>;
    userId: _UserId;
    analysisType: _AnalysisType;
    explanation: string;
    createdAt: _Timestamp;
    trustScore: number;
    reviewText: string;
    fakeScore: number;
    confidence: number;
}): {
    id: bigint;
    patterns: Array<string>;
    userId: UserId;
    analysisType: AnalysisType;
    explanation: string;
    createdAt: Timestamp;
    trustScore: number;
    reviewText: string;
    fakeScore: number;
    confidence: number;
} {
    return {
        id: value.id,
        patterns: value.patterns,
        userId: value.userId,
        analysisType: from_candid_AnalysisType_n5(_uploadFile, _downloadFile, value.analysisType),
        explanation: value.explanation,
        createdAt: value.createdAt,
        trustScore: value.trustScore,
        reviewText: value.reviewText,
        fakeScore: value.fakeScore,
        confidence: value.confidence
    };
}
function from_candid_record_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    token: string;
    userId: _UserId;
    role: _UserRole;
}): {
    token: string;
    userId: UserId;
    role: UserRole;
} {
    return {
        token: value.token,
        userId: value.userId,
        role: from_candid_UserRole_n42(_uploadFile, _downloadFile, value.role)
    };
}
function from_candid_record_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    userId: _UserId;
    role: _UserRole;
}): {
    userId: UserId;
    role: UserRole;
} {
    return {
        userId: value.userId,
        role: from_candid_UserRole_n42(_uploadFile, _downloadFile, value.role)
    };
}
function from_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    trusted: null;
} | {
    caution: null;
} | {
    risky: null;
}): TrustBadge {
    return "trusted" in value ? TrustBadge.trusted : "caution" in value ? TrustBadge.caution : "risky" in value ? TrustBadge.risky : value;
}
function from_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: boolean;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: boolean;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _TrustBadgeResult;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: TrustBadgeResult;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_TrustBadgeResult_n17(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _ReviewAnalysis;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: ReviewAnalysis;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_ReviewAnalysis_n3(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _PlatformStats;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: PlatformStats;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: Array<_AdminUserEntry>;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: Array<AdminUserEntry>;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_vec_n23(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    customer: null;
} | {
    seller: null;
}): Variant_admin_customer_seller {
    return "admin" in value ? Variant_admin_customer_seller.admin : "customer" in value ? Variant_admin_customer_seller.customer : "seller" in value ? Variant_admin_customer_seller.seller : value;
}
function from_candid_variant_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _DashboardStats;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: DashboardStats;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: Array<_SuspiciousProduct>;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: Array<SuspiciousProduct>;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: Array<_ReviewAnalysis>;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: Array<ReviewAnalysis>;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_vec_n34(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: Array<_ProductCheck>;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: Array<ProductCheck>;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_vec_n37(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _LoginResult;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: LoginResult;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_LoginResult_n40(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _SignupResult;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: SignupResult;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _SessionInfo;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: SessionInfo;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_SessionInfo_n49(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    manual: null;
} | {
    product: null;
}): AnalysisType {
    return "manual" in value ? AnalysisType.manual : "product" in value ? AnalysisType.product : value;
}
function from_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _ProductCheck;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: ProductCheck;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_ProductCheck_n9(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_vec_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_AdminUserEntry>): Array<AdminUserEntry> {
    return value.map((x)=>from_candid_AdminUserEntry_n24(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ReviewAnalysis>): Array<ReviewAnalysis> {
    return value.map((x)=>from_candid_ReviewAnalysis_n3(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ProductCheck>): Array<ProductCheck> {
    return value.map((x)=>from_candid_ProductCheck_n9(_uploadFile, _downloadFile, x));
}
function to_candid_UserRole_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n44(_uploadFile, _downloadFile, value);
}
function to_candid_variant_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Variant_admin_customer_seller): {
    admin: null;
} | {
    customer: null;
} | {
    seller: null;
} {
    return value == Variant_admin_customer_seller.admin ? {
        admin: null
    } : value == Variant_admin_customer_seller.customer ? {
        customer: null
    } : value == Variant_admin_customer_seller.seller ? {
        seller: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
